project:
  type: website
  output-dir: docs
  
website:
  title: "Sarahs-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://sbyoung225-hue.github.io/Sarahs-Website/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Sarah Young"

format:
  html:
    theme: solar
    toc: true

editor: source

